--刪除資料表
DROP TABLE　EMPLOYEE;  --僱工
DROP TABLE　DEPARTMENT;  --部門
--資料表建立 EMPLOYEE
CREATE TABLE EMPLOYEE
(EMP_NO   VARCHAR(10) NOT NULL PRIMARY KEY,
EMP_NAME  VARCHAR(10),
EMP_AGE   INT,
DEP_ID    VARCHAR(10)
);
--資料表建立 DEPARTMENT
CREATE TABLE DEPARTMENT
(DEP_ID VARCHAR(10) NOT NULL PRIMARY KEY,
DEP_N   VARCHAR(10)
);
--新增資料內容 EMPLOYEE
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('5','甲',20,'02');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('79','乙',42,'01');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('123','丙',60,'03');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('4561','丁',31,'01');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('85214','戊',53,'02');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_AGE,DEP_ID) VALUES ('451263','已',35,'07');
--新增資料內容 DEPARTMENT
INSERT INTO DEPARTMENT(DEP_ID,DEP_N) VALUES ('01','財務');
INSERT INTO DEPARTMENT(DEP_ID,DEP_N) VALUES ('02','行銷');
INSERT INTO DEPARTMENT(DEP_ID,DEP_N) VALUES ('03','資訊');
INSERT INTO DEPARTMENT(DEP_ID,DEP_N) VALUES ('04','人事');


