--SELECT 
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
--COUNT 
SELECT COUNT(DEP_ID) FROM EMPLOYEE;--6
SELECT COUNT(DEP_ID) FROM DEPARTMENT;--4
SELECT COUNT(1) FROM EMPLOYEE, DEPARTMENT;--24,WHY??
--DISTINCT (+)
SELECT DISTINCT A.DEP_ID FROM EMPLOYEE A,DEPARTMENT B
WHERE A.DEP_ID = B.DEP_ID(+) ORDER BY A.DEP_ID;--1,2,3,7
--DISTINCT LEFT JOIN
SELECT DISTINCT A.DEP_ID FROM　DEPARTMENT A
LEFT JOIN EMPLOYEE B ON A.DEP_ID = B.DEP_ID ORDER BY A.DEP_ID;--1,2,3,4


